const OFFICIAL={home:'https://www.schumacher-online.com/de',catalog:'https://www.schumacher-online.com/web/downloads/deutsch/Gesamtkatalog/DRS_Gesamtkatalog_2026.pdf',sheets:'https://www.schumacher-online.com/de/downloads/datenblaetter',images:'https://www.schumacher-online.com/de/downloads/produktbilder',plans:'https://www.schumacher-online.com/de/downloads/anleitungen-plaene'};
const PRODUCTS=[
{id:'aseptoman-med',sku:'ASE-MED',name:'ASEPTOMAN® MED',category:'hands',kind:'Händedesinfektion',spectrum:['begrenzt viruzid PLUS'],summary:'Alkoholisches Händedesinfektionsmittel für die tägliche hygienische und chirurgische Händedesinfektion.',facts:['wirksam innerhalb von 30 Sekunden gegen Noro-, Adeno- und Rotaviren','hautfreundlich durch pflegende Rückfetter','frei von quartären Ammoniumverbindungen'],color:'#0876d1'},
{id:'aseptoman-gel',sku:'ASE-GEL',name:'ASEPTOMAN® GEL',category:'hands',kind:'Händedesinfektionsgel',spectrum:['begrenzt viruzid'],summary:'Gelförmiges Präparat für eine einfache und kontrollierte Händedesinfektion.',facts:['angenehme Gelkonsistenz','für häufige Anwendung','übersichtliche Dosierung'],color:'#0876d1'},
{id:'descoderm',sku:'DESCO-DERM',name:'DESCODERM',category:'hands',kind:'Händedesinfektion',spectrum:['begrenzt viruzid'],summary:'Farbstoff- und parfümfreies Händedesinfektionsmittel.',facts:['für sensible Haut','schnelle Anwendung','für medizinische Bereiche'],color:'#0876d1'},
{id:'descosept-sensitive',sku:'DES-SENS',name:'DESCOSEPT SENSITIVE',category:'surface',kind:'Gebrauchsfertige Flächendesinfektion',spectrum:['begrenzt viruzid PLUS'],summary:'Gebrauchsfertige alkoholische Schnelldesinfektion für materialempfindliche Flächen.',facts:['schnell trocknend','für patientennahe Flächen','gute Materialverträglichkeit'],color:'#44ad45'},
{id:'descosept-spezial',sku:'DES-SP',name:'DESCOSEPT SPEZIAL',category:'surface',kind:'Gebrauchsfertige Flächendesinfektion',spectrum:['begrenzt viruzid'],summary:'Alkoholfreie gebrauchsfertige Reinigung und Desinfektion.',facts:['ohne Alkohole, Aldehyde und Phenole','für empfindliche Oberflächen','reinigend und desinfizierend'],color:'#44ad45'},
{id:'descosept-sensitive-wipes',sku:'DES-WIP',name:'DESCOSEPT SENSITIVE WIPES',category:'surface',kind:'Reinigungs- und Desinfektionstücher',spectrum:['begrenzt viruzid PLUS'],summary:'Gebrauchsfertige Tücher mit patentierter Tuchfaltung.',facts:['schnelle Einzelentnahme','für mittelgroße Flächen','Bio-Vlies-Variante verfügbar'],color:'#44ad45'},
{id:'ultrasol-oxy',sku:'ULT-OXY',name:'ULTRASOL OXY®',category:'surface',kind:'Flächendesinfektion',spectrum:['viruzid','sporizid'],summary:'Oxidative Reinigung und Desinfektion mit sehr breitem Wirkungsspektrum.',facts:['viruzid und sporizid','hohe Materialverträglichkeit','kurze Einwirkzeiten'],color:'#44ad45'},
{id:'ultrasol-active',sku:'ULT-ACT',name:'ULTRASOL® ACTIVE',category:'surface',kind:'Desinfektionsmittel-Konzentrat',spectrum:['viruzid','sporizid'],summary:'Pulverkonzentrat für anspruchsvolle Flächendesinfektion.',facts:['praktisch staubfrei','breites Wirkungsspektrum','gute Reinigungsleistung'],color:'#44ad45'},
{id:'perfektan-active',sku:'PER-ACT',name:'PERFEKTAN® ACTIVE',category:'instruments',kind:'Manuelle Instrumentenaufbereitung',spectrum:['viruzid'],summary:'Konzentrat zur manuellen Reinigung und Desinfektion medizinischer Instrumente.',facts:['für Tauchbadverfahren','breites Wirkungsspektrum','materialschonend anwenden'],color:'#7956b3'},
{id:'descoton-extra',sku:'DES-EX',name:'DESCOTON EXTRA',category:'instruments',kind:'Instrumentendesinfektion',spectrum:['begrenzt viruzid PLUS'],summary:'Präparat für die manuelle Aufbereitung von Instrumenten.',facts:['reinigend und desinfizierend','für medizinische Instrumente','Dosierung gemäß Produktinformation'],color:'#7956b3'},
{id:'esh-spender',sku:'ESH-SP',name:'ESH Spendersystem',category:'application',kind:'Spender und Applikation',spectrum:[],summary:'Hygienisches Spendersystem für Hände- und Hautpräparate.',facts:['farbkodierte Anwendung','optimierte Restentleerung','für Vacu-Bag-Systeme'],color:'#ef829a'},
{id:'wipes-spender',sku:'WIP-SP',name:'Vliestuch-Spendersystem',category:'application',kind:'Spender und Applikation',spectrum:[],summary:'Wiederverwendbares System für getränkte Vliestücher.',facts:['einfache Anwendung','verschiedene Größen','Aufbereitungshinweise beachten'],color:'#ef829a'}
];
let state={screen:'prices',priceList:localStorage.getItem('priceList')||'',category:'all',query:'',spectrum:'all',prices:JSON.parse(localStorage.getItem('prices')||'{}'),selected:null};
const $=s=>document.querySelector(s); const money=v=>v==null||v===''?'Preis nicht hinterlegt':new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(v));
function header(back=false){return `<header class="topbar">${back?'<button class="back" data-action="back">←</button>':''}<img class="logo" src="public/assets/dr-schumacher-logo.png" alt="Dr. Schumacher"><div class="grow"></div>${state.priceList?`<button class="active-list" data-action="prices">${state.priceList}</button>`:''}</header>`}
function render(){const app=$('#app'); if(state.screen==='prices')app.innerHTML=priceScreen(); else if(state.screen==='menu')app.innerHTML=header()+menuScreen(); else if(state.screen==='products')app.innerHTML=header(true)+productsScreen(); else app.innerHTML=header(true)+detailScreen(); bind();}
function priceScreen(){let opts=['UVP','FH 1','FH 2','FH 3','FH 4','FH 5'];return `<main class="shell"><div class="page hero"><img class="logo" src="public/assets/dr-schumacher-logo.png"><h1>Welche Preisliste soll verwendet werden?</h1><p>Die Auswahl gilt für alle Produkte und kann später jederzeit geändert werden.</p><div class="price-grid">${opts.map(x=>`<button class="price-card ${state.priceList===x?'selected':''}" data-price="${x}">${x}</button>`).join('')}</div><button class="primary" data-action="start" ${!state.priceList?'disabled':''}>App starten</button><section class="admin-box"><h2>Preise aus Excel einlesen</h2><p>Spalten: <b>Artikelnummer, Produktname, Gebinde, UVP, FH 1, FH 2, FH 3, FH 4, FH 5</b></p><input id="excel" type="file" accept=".xlsx,.xls,.csv"><p id="importStatus" class="small">Die Preise bleiben nur auf diesem Gerät gespeichert.</p></section></div></main>`}
function menuScreen(){const cards=[['surface','🧼','Fläche','Desinfektion und Reinigung'],['hands','✋','Hände & Haut','Händedesinfektion, Hautschutz und Reinigung'],['instruments','🧪','Instrumente','Manuelle und maschinelle Aufbereitung'],['application','🧴','Applikation','Spender, Halter und Dosierhilfen'],['all','📚','Produktübersicht','Alle Produkte im Überblick'],['downloads','⬇️','Aktuelle Downloads','Katalog, Datenblätter, Bilder und Pläne']];return `<main class="page"><div class="hero"><h1>Was möchten Sie zeigen?</h1><p>Große Bereiche, wenige Klicks und immer die aktive Preisliste.</p></div><div class="category-grid">${cards.map(c=>`<button class="category ${c[0]}" data-category="${c[0]}"><span class="emoji">${c[1]}</span><span><h2>${c[2]}</h2><p>${c[3]}</p></span></button>`).join('')}</div></main><div class="footer">Interne Anwendung · Öffentliche Dokumente werden direkt bei Dr. Schumacher geöffnet.</div>`}
function productsScreen(){if(state.category==='downloads')return downloadsScreen();let names={surface:'Fläche',hands:'Hände & Haut',instruments:'Instrumente',application:'Applikation',all:'Alle Produkte'};let spectra=['all','begrenzt viruzid','begrenzt viruzid PLUS','viruzid','sporizid'];let list=PRODUCTS.filter(p=>(state.category==='all'||p.category===state.category)&&(!state.query||`${p.name} ${p.kind} ${p.sku}`.toLowerCase().includes(state.query.toLowerCase()))&&(state.spectrum==='all'||p.spectrum.includes(state.spectrum)));return `<main class="page"><h1>${names[state.category]}</h1><input class="search" id="search" value="${state.query}" placeholder="Produktname oder Artikelnummer suchen"><div class="filter-row">${spectra.map(s=>`<button class="chip ${state.spectrum===s?'active':''}" data-spectrum="${s}">${s==='all'?'Alle Wirkspektren':s}</button>`).join('')}</div><div class="product-grid">${list.map(productCard).join('')||'<p>Keine Produkte gefunden.</p>'}</div></main>`}
function productCard(p){let price=state.prices[p.sku]?.[state.priceList];return `<article class="product-card" data-product="${p.id}"><div class="product-top" style="background:${p.color}"></div><div class="product-body"><span class="small">${p.kind}</span><h3>${p.name}</h3>${p.spectrum.map(s=>`<span class="badge" style="background:${s.includes('PLUS')?'#18a34a':s==='viruzid'?'#df2f35':s==='sporizid'?'#7448a8':'#0876d1'}">${s}</span>`).join('')}<p>${p.summary}</p><div class="product-price">${money(price)}</div><span class="small">${state.priceList}</span></div></article>`}
function detailScreen(){let p=PRODUCTS.find(x=>x.id===state.selected),row=state.prices[p.sku]||{},price=row[state.priceList];return `<main class="page"><div class="detail"><div class="detail-visual">${p.category==='hands'?'✋':p.category==='surface'?'🧼':p.category==='instruments'?'🧪':'🧴'}</div><section><span class="small">${p.kind} · ${p.sku}</span><h1>${p.name}</h1><p>${p.summary}</p>${p.spectrum.map(s=>`<span class="badge" style="background:${s.includes('PLUS')?'#18a34a':s==='viruzid'?'#df2f35':s==='sporizid'?'#7448a8':'#0876d1'}">${s}</span>`).join('')}<ul class="facts">${p.facts.map(f=>`<li>✓ ${f}</li>`).join('')}</ul><div class="price-box">${money(price)}<div class="small">Aktive Preisliste: ${state.priceList}${row.Gebinde?' · '+row.Gebinde:''}</div></div><div class="notice">Verbindliche Anwendung, Wirksamkeit und Sicherheit bitte immer anhand der aktuellen offiziellen Produktinformation prüfen.</div><div class="links-grid"><a class="link-card" target="_blank" href="${OFFICIAL.sheets}">📄 Aktuelle Datenblätter</a><a class="link-card" target="_blank" href="${OFFICIAL.images}">🖼️ Aktuelle Produktbilder</a><a class="link-card" target="_blank" href="${OFFICIAL.catalog}">📘 Gesamtkatalog 2026</a><a class="link-card" target="_blank" href="${OFFICIAL.home}">🌐 Produkt auf Website suchen</a></div></section></div></main>`}
function downloadsScreen(){return `<main class="page"><h1>Aktuelle Downloads</h1><p>Diese Schaltflächen öffnen immer die aktuell online bereitgestellten Inhalte.</p><div class="links-grid"><a class="link-card" target="_blank" href="${OFFICIAL.catalog}">📘 Gesamtkatalog 2026</a><a class="link-card" target="_blank" href="${OFFICIAL.sheets}">📄 Produkt- und Sicherheitsdatenblätter</a><a class="link-card" target="_blank" href="${OFFICIAL.images}">🖼️ Produktbilder</a><a class="link-card" target="_blank" href="${OFFICIAL.plans}">📋 Anleitungen und Pläne</a><a class="link-card" target="_blank" href="${OFFICIAL.home}">🌐 Dr. Schumacher Website</a></div></main>`}
function bind(){document.querySelectorAll('[data-price]').forEach(b=>b.onclick=()=>{state.priceList=b.dataset.price;localStorage.setItem('priceList',state.priceList);render()});document.querySelector('[data-action="start"]')?.addEventListener('click',()=>{state.screen='menu';render()});document.querySelector('[data-action="prices"]')?.addEventListener('click',()=>{state.screen='prices';render()});document.querySelector('[data-action="back"]')?.addEventListener('click',()=>{state.screen=state.screen==='detail'?'products':'menu';render()});document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;state.screen='products';state.query='';state.spectrum='all';render()});document.querySelectorAll('[data-spectrum]').forEach(b=>b.onclick=()=>{state.spectrum=b.dataset.spectrum;render()});document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.product;state.screen='detail';render()});$('#search')?.addEventListener('input',e=>{state.query=e.target.value;render()});$('#excel')?.addEventListener('change',importExcel)}
async function importExcel(e){let status=$('#importStatus'),file=e.target.files[0];if(!file)return;if(typeof XLSX==='undefined'){status.textContent='Excel-Modul konnte nicht geladen werden. Bitte Internetverbindung prüfen.';return}try{let data=await file.arrayBuffer(),wb=XLSX.read(data),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});let mapped={};for(const r of rows){let sku=String(r.Artikelnummer||r.SKU||r['Artikel-Nr.']||'').trim();if(!sku)continue;mapped[sku]={Gebinde:r.Gebinde||'',UVP:toNumber(r.UVP),'FH 1':toNumber(r['FH 1']),'FH 2':toNumber(r['FH 2']),'FH 3':toNumber(r['FH 3']),'FH 4':toNumber(r['FH 4']),'FH 5':toNumber(r['FH 5'])}}state.prices=mapped;localStorage.setItem('prices',JSON.stringify(mapped));let hits=PRODUCTS.filter(p=>mapped[p.sku]).length;status.textContent=`${Object.keys(mapped).length} Preiszeilen eingelesen, ${hits} App-Produkte zugeordnet.`}catch(err){status.textContent='Import fehlgeschlagen: '+err.message}}
function toNumber(v){if(v===''||v==null)return '';if(typeof v==='number')return v;return Number(String(v).replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))}
render(); if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
